package cn.ibizlab.pms.ibiz.logic.ibztestsuiteactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.IBZTestSuiteAction ibztestsuiteactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IIBZTestSuiteActionService iBzSysIbztestsuiteactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "ibztestsuiteactioncommentprepareparam1"
            when
            then
                                ibztestsuiteactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            ibztestsuiteactioncommentdefault.set("product","0");
                            ibztestsuiteactioncommentdefault.set("project","0");
                            ibztestsuiteactioncommentdefault.set("read","0");
                            ibztestsuiteactioncommentdefault.set("action","commented");
                            ibztestsuiteactioncommentdefault.set("extra","");
                        update(ibztestsuiteactioncommentdefault);//更新fact中变量值
            end

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ibztestsuiteactioncommentbegin"
            when
            then
            end