server:
  port: 10130
#Log配置
logging:
  level:
    cn.ibizlab.pms: info
#zuul网关路由设置
zuul:
  routes:
    zt_branch:
      path: /branches/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_user:
      path: /users/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_favorites:
      path: /ibzfavorites/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_projectteam:
      path: /projectteams/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_build:
      path: /builds/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_task:
      path: /tasks/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_module:
      path: /modules/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_product:
      path: /products/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_action:
      path: /actions/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_casestep:
      path: /casesteps/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_productline:
      path: /productlines/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_release:
      path: /releases/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_taskteam:
      path: /taskteams/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_productmodule:
      path: /productmodules/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_project:
      path: /projects/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_todo:
      path: /todos/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_story:
      path: /stories/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_myterritory:
      path: /ibzmyterritories/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_case:
      path: /cases/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_testmodule:
      path: /testmodules/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_productplan:
      path: /productplans/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_projectstats:
      path: /projectstats/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_bug:
      path: /bugs/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_projectmodule:
      path: /projectmodules/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_productstats:
      path: /productstats/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_testtask:
      path: /testtasks/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_testsuite:
      path: /testsuites/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    loginv7:
      path: /v7/login
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
      stripPrefix: false
    changepwd:
      path: /v7/changepwd
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
      stripPrefix: false
    uaa:
      path: /uaa/**
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
      stripPrefix: false
    config:
      path: /config/**
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
      stripPrefix: false
    oucore:
      path: /ibzorganizations/**
      serviceId: ${ibiz.ref.service.ou:ibzou-api}
      stripPrefix: false
    oudict:
      path: /dictionarys/**/Ibzou**
      serviceId: ${ibiz.ref.service.ou:ibzou-api}
      stripPrefix: false
    ou:
      path: /ibzdepartments/**
      serviceId: ${ibiz.ref.service.ou:ibzou-api}
      stripPrefix: false
    uaadict:
      path: /dictionarys/**/SysOperator
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
      stripPrefix: false
    dict:
      path: /dictionarys/**
      serviceId: ${ibiz.ref.service.dict:ibzdict-api}
      stripPrefix: false
    disk:
      path: /net-disk/**
      serviceId: ${ibiz.ref.service.disk:ibzdisk-api}
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
