server:
  port: 10130
#Log配置
logging:
  level:
    cn.ibizlab.pms: info
#zuul网关路由设置
zuul:
  routes:
    zt_user:
      path: /users/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_projectteam:
      path: /projectteams/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_build:
      path: /builds/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_task:
      path: /tasks/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_product:
      path: /products/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_action:
      path: /actions/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_casestep:
      path: /casesteps/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_release:
      path: /releases/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_taskteam:
      path: /taskteams/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_project:
      path: /projects/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_todo:
      path: /todos/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_story:
      path: /stories/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_myterritory:
      path: /ibzmyterritories/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_case:
      path: /cases/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_productplan:
      path: /productplans/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_projectstats:
      path: /projectstats/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_bug:
      path: /bugs/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_productstats:
      path: /productstats/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_testtask:
      path: /testtasks/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_testsuite:
      path: /testsuites/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
