export default [
    'logincnt',
    'openedstorycnt',
    'ztdate',
    'date',
    'closedstorycnt',
    'openedbugcnt',
    'loghours',
    'dynamiccnt',
    'finishedtaskcnt',
    'resolvedbugcnt',
    'comment',
    'openedtaskcnt',
    'id',
];
