export default [
    'ibizproprojectdailyname',
    'tasks',
    'begin',
    'createdate',
    'end',
    'createman',
    'date',
    'totalestimates',
    'updateman',
    'pm',
    'updatedate',
    'ibizproprojectdailyid',
    'projectname',
    'project',
];
