export default [
    'version',
    'type',
    'createman',
    'downloadcount',
    'createdate',
    'downloadurl',
    'updatedate',
    'tag',
    'score',
    'ibizpropluginname',
    'ibizpropluginid',
    'keyword',
    'updateman',
    'commentcount',
];
