package cn.ibizlab.pms.ibiz.logic.ibzproproductactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.IBZProProductAction ibzproproductactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IIBZProProductActionService iBzSysIbzproproductactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "ibzproproductactioncommentprepareparam1"
            when
            then
                                ibzproproductactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            ibzproproductactioncommentdefault.set("product","0");
                            ibzproproductactioncommentdefault.set("project","0");
                            ibzproproductactioncommentdefault.set("read","0");
                            ibzproproductactioncommentdefault.set("action","commented");
                            ibzproproductactioncommentdefault.set("extra","");
                        update(ibzproproductactioncommentdefault);//更新fact中变量值
            end

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ibzproproductactioncommentbegin"
            when
            then
            end