zentao:
  url: http://172.16.180.217/zentao/
  needretry: false
  retrycount: 0
  file:
    uploadpath: ibizutil/ztupload
#    downloadpath: ibizutil/ztdownload/{id}
ibiz:
  auth:
    service: IBZUAAZTUserService
