zentao:
  url: http://172.16.180.217/zentao/
  needretry: false
  retrycount: 0
  file:
    uploadpath: ibizutil/ztupload
#    downloadpath: ibizutil/ztdownload/{id}

environment:
  - TZ=Asia/Shanghai


#API替换相关配置。
ibiz:
  # 是否使用UAA认证。
  uaa: true
  auth:
    #本地用户认证：IBZZTUserService
    #UAA认证：IBZUAAZTUserService
    service: IBZUAAZTUserService
    token:
    # 本地ZT账户认证模式：SimpleTokenUtil
    # UAA认证模式：SimpleTokenUtil
      util: UAATokenUtil
  ref:
    service:
      uaa: ibzuaa-api-pms

