zentao:
  url: http://172.16.180.217/zentao/
  needretry: false
  retrycount: 0
  file:
    uploadpath: ibizutil/ztupload
#    downloadpath: ibizutil/ztdownload/{id}

environment:
  - TZ=Asia/Shanghai


#API替换相关配置。
ibiz:
  auth:
    #本地用户认证：IBZZTUserService
    #UAA认证：IBZUAAUserService
    service: IBZUAAUserService
    token:
    # 本地ZT账户认证模式：SimpleTokenUtil
    # UAA认证模式：UAATokenUtil
      util: UAATokenUtil
  ref:
    service:
      uaa: ibzuaa-apipms
      ou: ibzou-apipms
  cacheLevel: L2
spring:
  servlet:
    multipart:
      # 代表文件上传最大大小
      max-file-size: 100MB
      # 代表文件上传最大总大小
      max-request-size: 1024MB
hystrix:
  metrics:
    polling-interval-ms:

pms:
  # 启动时，批量同步资源。
  batchsync:
    #同步用户、组织、部门资源
    ou: false
    #同步权限资源。
    uaa: true