zentao:
  url: http://172.16.102.102/zentao/
  needretry: false
  retrycount: 0
  file:
    uploadpath: ibizutil/ztupload
#    downloadpath: ibizutil/ztdownload/{id}
ibiz:
  auth:
    service: IBZUAAZTUserService
environment:
  - TZ=Asia/Shanghai
