export const themeConfig = {
    types: [{
        label: '应用',
        value: 'app',
        className: '',
        disable: false,
        items: [{
            label: '背景色',
            cssName: '--app-background-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '背景色（淡色）',
            cssName: '--app-background-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '背景色（亮色）',
            cssName: '--app-background-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '底部背景色',
            cssName: '--app-footer-background-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色',
            cssName: '--app-font-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色（淡色）',
            cssName: '--app-font-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色（深色）',
            cssName: '--app-font-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        }]
    }, {
        label: '侧边栏',
        value: 'leftsidebar',
        className: '',
        disable: false,
        items: [{
            label: '背景色',
            cssName: '--leftsidebar-background-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '背景色（淡色）',
            cssName: '--leftsidebar-background-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '背景色（亮色）',
            cssName: '--leftsidebar-background-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色',
            cssName: '--leftsidebar-font-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色（淡色）',
            cssName: '--leftsidebar-font-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色（亮色）',
            cssName: '--leftsidebar-font-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        }]
    }, {
        label: '按钮',
        value: 'button',
        className: '',
        disable: false,
        items: [{
            label: '不常用操作背景色',
            cssName: '--button-background-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '一般操作背景色',
            cssName: '--button-background-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '关键操作背景色',
            cssName: '--button-background-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '不常用操作字体颜色',
            cssName: '--button-font-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '一般操作字体颜色',
            cssName: '--button-font-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '关键操作字体颜色',
            cssName: '--button-font-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        }]
    }, {
        label: '视图',
        value: 'view',
        className: '',
        disable: true,
        items: [{
            label: '背景色',
            cssName: '--view-background-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '背景色（淡色）',
            cssName: '--view-background-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '背景色（亮色）',
            cssName: '--view-background-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色',
            cssName: '--view-font-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色（淡色）',
            cssName: '--view-font-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色（亮色）',
            cssName: '--view-font-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        },]
    }, {
        label: '部件',
        value: 'ctrl',
        className: '',
        disable: true,
        items: [{
            label: '背景色',
            cssName: '--ctrl-background-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '背景色（淡色）',
            cssName: '--ctrl-background-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '背景色（亮色）',
            cssName: '--ctrl-background-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色',
            cssName: '--ctrl-font-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色（淡色）',
            cssName: '--ctrl-font-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '字体颜色（亮色）',
            cssName: '--ctrl-font-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '选中颜色',
            cssName: '--ctrl-select-color',
            default: '',
            disable: false,
            showAlpha: true
        }]
    }, {
        label: '其他',
        value: 'other',
        className: '',
        disable: false,
        items: [{
            label: '部件字体颜色',
            cssName: '--ctrl-font-color',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '部件字体颜色（淡色）',
            cssName: '--ctrl-font-color-light',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '部件字体颜色（亮色）',
            cssName: '--ctrl-font-color-bright',
            default: '',
            disable: false,
            showAlpha: true
        }, {
            label: '选中颜色',
            cssName: '--ctrl-select-color',
            default: '',
            disable: false,
            showAlpha: true
        },]
    }]
}