zuul:
  routes:
    common:
      path: /**
      serviceId: pms-webapi
      stripPrefix: false
#    v7:
#      path: /v7/**
#      serviceId: pms-webapi-qml
#      stripPrefix: false
#    ibizutil:
#      path: /ibizutil/**
#      serviceId: pms-webapi-qml
#      stripPrefix: false

environment:
  - TZ=Asia/Shanghai

ibiz:
  permitall: true
  ref:
    service:
      pms-webapi: pms-webapi
      uaa: ibzuaa-api-ldap
  auth:
    token:
      # 本地ZT账户认证模式：SimpleTokenUtil
      # UAA认证模式：UAATokenUtil
      util: UAATokenUtil
#    service: ZTUserService