zuul:
  routes:
    v7:
      path: /v7/**
      serviceId: pms-webapi-uaa
      stripPrefix: false
    ibizutil:
      path: /ibizutil/**
      serviceId: pms-webapi-uaa
      stripPrefix: false
environment:
  - TZ=Asia/Shanghai


ibiz:
  ref:
    service:
      pms-webapi: pms-webapi-uaa
      uaa: ibzuaa-api-ldap
  auth:
    token:
      # 本地ZT账户认证模式：SimpleTokenUtil
      # UAA认证模式：SimpleTokenUtil
      util: UAATokenUtil
#      util: SimpleTokenUtil
#    service: IBZUAAZTUserService