zuul:
  routes:
    v7:
      path: /v7/**
      serviceId: pms-webapi
      stripPrefix: false
    ibizutil:
      path: /ibizutil/**
      serviceId: pms-webapi
      stripPrefix: false
environment:
  - TZ=Asia/Shanghai
