server:
  port: 10120
#Log配置
logging:
  level:
    cn.ibizlab.pms: info
#zuul网关路由设置
zuul:
  routes:
    zt_productplan:
      path: /productplans/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_projectproduct:
      path: /projectproducts/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_case:
      path: /cases/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_taskteam:
      path: /ibztaskteams/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibztaskestimate:
      path: /ibztaskestimates/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_product:
      path: /products/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_taskteam:
      path: /taskteams/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_file:
      path: /files/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_suitecase:
      path: /suitecases/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_burn:
      path: /burns/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_subproductplan:
      path: /subproductplans/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_storyspec:
      path: /storyspecs/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_usertpl:
      path: /usertpls/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_branch:
      path: /branches/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_productstats:
      path: /productstats/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_projectmember:
      path: /ibzprojectmembers/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_action:
      path: /actions/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_group:
      path: /groups/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_casestep:
      path: /casesteps/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_dept:
      path: /depts/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_company:
      path: /companies/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_casestep:
      path: /ibzcasesteps/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_taskestimate:
      path: /taskestimates/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_story:
      path: /stories/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_todo:
      path: /todos/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_subtask:
      path: /subtasks/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_project:
      path: /projects/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_history:
      path: /histories/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_user:
      path: /users/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_doclib:
      path: /doclibs/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_productmodule:
      path: /productmodules/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_module:
      path: /modules/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_testmodule:
      path: /testmodules/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_productlife:
      path: /productlives/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_task:
      path: /tasks/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_build:
      path: /builds/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_testresult:
      path: /testresults/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_testsuite:
      path: /testsuites/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_projectteam:
      path: /projectteams/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_testtask:
      path: /testtasks/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_productline:
      path: /productlines/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_testreport:
      path: /testreports/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_projectstats:
      path: /projectstats/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_testrun:
      path: /testruns/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_myterritory:
      path: /ibzmyterritories/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_bug:
      path: /bugs/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_projectmodule:
      path: /projectmodules/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    ibz_doc:
      path: /ibzdocs/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    zt_release:
      path: /releases/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
    dynadashboard:
      path: /dynadashboards/**
      serviceId: ${ibiz.ref.service.pms-webapi:pms-webapi}
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
