zuul:
  routes:
    v7:
      path: /v7/**
      # 登录直接请求UAA登录。
      serviceId: ibzuaa-api-ldap
      stripPrefix: false
    ibizutil:
      path: /ibizutil/**
      serviceId: pms-webapi
      stripPrefix: false
environment:
  - TZ=Asia/Shanghai


ibiz:
  ref:
    service:
      pms-webapi: pms-webapi
      uaa: ibzuaa-api-ldap
  auth:
    token:
#      util: ZTUAATokenUtil
      util: UAATokenUtil
