package cn.ibizlab.pms.ibiz.logic.ibzprobuildactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.IbzProBuildAction ibzprobuildactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IIbzProBuildActionService iBzSysIbzprobuildactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "ibzprobuildactioncommentprepareparam1"
            when
            then
                                ibzprobuildactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            ibzprobuildactioncommentdefault.set("product","0");
                            ibzprobuildactioncommentdefault.set("project","0");
                            ibzprobuildactioncommentdefault.set("read","0");
                            ibzprobuildactioncommentdefault.set("action","commented");
                            ibzprobuildactioncommentdefault.set("extra","");
                        update(ibzprobuildactioncommentdefault);//更新fact中变量值
            end

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ibzprobuildactioncommentbegin"
            when
            then
            end