package cn.ibizlab.pms.ibiz.logic.ibzprotodoactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.IBZProToDoAction ibzprotodoactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IIBZProToDoActionService iBzSysIbzprotodoactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ibzprotodoactioncommentbegin"
            when
            then
            end

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "ibzprotodoactioncommentprepareparam1"
            when
            then
                                ibzprotodoactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            ibzprotodoactioncommentdefault.set("product","0");
                            ibzprotodoactioncommentdefault.set("project","0");
                            ibzprotodoactioncommentdefault.set("read","0");
                            ibzprotodoactioncommentdefault.set("action","commented");
                            ibzprotodoactioncommentdefault.set("extra","");
                        update(ibzprotodoactioncommentdefault);//更新fact中变量值
            end