export default [
    'ibzdocid',
    'addedby',
    'editedby',
    'addeddate',
    'size',
    'lib',
    'createdate',
    'ibzdocname',
    'order',
    'iscollect',
    'createman',
    'updatedate',
    'editeddate',
    'objecttype',
    'updateman',
];
