global cn.ibizlab.pms.core.report.service.IIbzWeeklyService  ibzweeklyService;
global cn.ibizlab.pms.core.report.domain.IbzWeekly et;

    no-loop

    rule "ibzweeklycreategetlastweekplanandwork"
    ruleflow-group "FF6E81BD-184F-4672-9C88-76072CE0AC9A"
    when
    then
    cn.ibizlab.pms.core.report.domain.IbzWeekly actionLogicDE =new cn.ibizlab.pms.core.report.domain.IbzWeekly();
    et.copyTo(actionLogicDE,true);
    ibzweeklyService.createGetLastWeekPlanAndWork(actionLogicDE);
    end