global cn.ibizlab.pms.core.report.service.IIbzWeeklyService  ibzweeklyService;
global cn.ibizlab.pms.core.report.domain.IbzWeekly et;

    no-loop

    rule "ibzweeklycreategetlastweekplanandwork"
    ruleflow-group "ee489dc5e387396966aed140ac9e7218"
    when
    then
    cn.ibizlab.pms.core.report.domain.IbzWeekly actionLogicDE =new cn.ibizlab.pms.core.report.domain.IbzWeekly();
    et.copyTo(actionLogicDE,true);
    ibzweeklyService.createGetLastWeekPlanAndWork(actionLogicDE);
    end