package cn.ibizlab.pms.ibiz.logic.ibztaskactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.IBZTaskAction ibztaskactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IIBZTaskActionService iBzSysIbztaskactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "ibztaskactioncommentprepareparam1"
            when
            then
                                ibztaskactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            ibztaskactioncommentdefault.set("product","0");
                            ibztaskactioncommentdefault.set("project","0");
                            ibztaskactioncommentdefault.set("read","0");
                            ibztaskactioncommentdefault.set("action","commented");
                            ibztaskactioncommentdefault.set("extra","");
                        update(ibztaskactioncommentdefault);//更新fact中变量值
            end

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ibztaskactioncommentbegin"
            when
            then
            end