package cn.ibizlab.pms.ibiz.logic.ibzprobugactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.IbzProBugAction ibzprobugactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IIbzProBugActionService iBzSysIbzprobugactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "ibzprobugactioncommentprepareparam1"
            when
            then
                                ibzprobugactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            ibzprobugactioncommentdefault.set("product","0");
                            ibzprobugactioncommentdefault.set("project","0");
                            ibzprobugactioncommentdefault.set("read","0");
                            ibzprobugactioncommentdefault.set("action","commented");
                            ibzprobugactioncommentdefault.set("extra","");
                        update(ibzprobugactioncommentdefault);//更新fact中变量值
            end

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ibzprobugactioncommentbegin"
            when
            then
            end