---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibizpms-provider-standardapi
  labels:
    app: ibizpms-provider-standardapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibizpms-provider-standardapi
  template:
    metadata:
      labels:
        app: ibizpms-provider-standardapi
    spec:
      imagePullSecrets:
      - name: aly-shanghai
      containers:
      - name: ibizpms-provider-standardapi
        image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibizpms-provider-standardapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: ibizpms-provider-standardapi
  labels:
    app: ibizpms-provider-standardapi
spec:
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    nodePort: 8081
    protocol: TCP
  selector:
    app: ibizpms-provider-standardapi

