export default [
    'branch',
    'createman',
    'updatedate',
    'productlifename',
    'createdate',
    'parent',
    'year',
    'updateman',
    'type',
    'marker',
    'begin',
    'productlifeid',
    'end',
    'product',
];
