export default [
    'end',
    'date',
    'updatedate',
    'ibizproproductdailyname',
    'updateman',
    'createman',
    'tasks',
    'createdate',
    'ibizproproductdailyid',
    'totalestimates',
    'begin',
    'po',
    'productname',
    'product',
];
