ALTER TABLE `zt_product`
ADD COLUMN `orgname`  VARCHAR(100)  COMMENT '归属组织名' 
;
ALTER TABLE `zt_product`
ADD COLUMN `mdeptname`  VARCHAR(100)  COMMENT '归属部门名' 
;

ALTER TABLE `zt_project`
ADD COLUMN `MDEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_project`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' 
;

ALTER TABLE `zt_release`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_release`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_projectproduct`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_projectproduct`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_productplan`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名'
;

ALTER TABLE `zt_productplan`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_action`
ADD COLUMN `DEPT`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_action`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_action`
ADD COLUMN `ORG`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_action`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_BUG`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_bug`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_task`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_task`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_file`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_file`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_taskestimate`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_taskestimate`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_story`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_story`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_storyspec`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_storyspec`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_testtask`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_testtask`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_case`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_case`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_casestep`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_casestep`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_usercontact`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_usercontact`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_usertpl`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_usertpl`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_testreport`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_testreport`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_history`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_history`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_testsuite`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_testsuite`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_branch`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_branch`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_doclib`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_doclib`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;

ALTER TABLE `zt_build`
ADD COLUMN `DEPTNAME`  VARCHAR(100)  COMMENT '归属部门名' 
;
ALTER TABLE `zt_build`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名' ;


ALTER TABLE `zt_module`
ADD COLUMN `MDEPTNAME`  VARCHAR(100)  COMMENT '归属部门名'
;
ALTER TABLE `zt_module`
ADD COLUMN `ORGNAME`  VARCHAR(100)  COMMENT '归属组织名'
;