CREATE TABLE `T_IBZ_AGENT`(
`UPDATEMAN`  VARCHAR(60) COMMENT '更新人' 
,`CREATEMANNAME`  VARCHAR(100) COMMENT '创建人姓名' 
,`AGENTEND`  DATETIME COMMENT '代理结束日期' 
,`SRFID` INT AUTO_INCREMENT PRIMARY KEY
,`SRFDCID` VARCHAR(60)
,`IBZ_AGENTID`  BIGINT(100)  NOT NULL COMMENT '代理标识' 
,`CREATEMAN`  VARCHAR(60) COMMENT '建立人' 
,`UPDATEDATE`  DATETIME COMMENT '更新时间' 
,`AGENTUSER`  VARCHAR(100) COMMENT '代理用户' 
,`CREATEDATE`  DATETIME COMMENT '建立时间' 
,`AGENTBEGIN`  DATETIME COMMENT '代理开始日期' 
,`IBZ_AGENTNAME`  VARCHAR(200) COMMENT '代理名称' 
)COMMENT='代理';