global cn.ibizlab.pms.core.report.service.IIbzMonthlyService  ibzmonthlyService;
global cn.ibizlab.pms.core.report.domain.IbzMonthly et;

    no-loop

    rule "ibzmonthlycreateusermonthly"
    ruleflow-group "5f64047ab3a396a4c77aa5cfdab38c52"
    when
    then
    cn.ibizlab.pms.core.report.domain.IbzMonthly actionLogicDE =new cn.ibizlab.pms.core.report.domain.IbzMonthly();
    et.copyTo(actionLogicDE,true);
    ibzmonthlyService.createUserMonthly(actionLogicDE);
    end