package cn.ibizlab.pms.ibiz.logic.ibzproreportlyactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.IbzProReportlyAction ibzproreportlyactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IIbzProReportlyActionService iBzSysIbzproreportlyactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "ibzproreportlyactioncommentprepareparam1"
            when
            then
                                ibzproreportlyactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            ibzproreportlyactioncommentdefault.set("product","0");
                            ibzproreportlyactioncommentdefault.set("project","0");
                            ibzproreportlyactioncommentdefault.set("read","0");
                            ibzproreportlyactioncommentdefault.set("action","commented");
                            ibzproreportlyactioncommentdefault.set("extra","");
                        update(ibzproreportlyactioncommentdefault);//更新fact中变量值
            end

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ibzproreportlyactioncommentbegin"
            when
            then
            end