export default [
    'date',
    'year',
    'consumed',
    'evaluationstatus',
    'account',
    'id',
    'monthname',
    'name',
    'yearname',
    'evaluationtime',
    'evaluationcost',
    'inputcost',
    'month',
    'taskcnt',
];
