global cn.ibizlab.pms.core.report.service.IIbzMonthlyService  ibzmonthlyService;
import cn.ibizlab.pms.util.helper.CachedBeanCopier;
global cn.ibizlab.pms.core.report.domain.IbzMonthly et;

    no-loop
    rule "ibzmonthlycreateusermonthly"
    ruleflow-group "5f64047ab3a396a4c77aa5cfdab38c52"
    when
    then
    cn.ibizlab.pms.core.report.domain.IbzMonthly actionLogicDE =new cn.ibizlab.pms.core.report.domain.IbzMonthly();
    CachedBeanCopier.copy(et, actionLogicDE);
    ibzmonthlyService.createUserMonthly(actionLogicDE);
    end

