package cn.ibizlab.pms.ibiz.logic.ibzpromonthlyactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.IbzProMonthlyAction ibzpromonthlyactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IIbzProMonthlyActionService iBzSysIbzpromonthlyactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ibzpromonthlyactioncommentbegin"
            when
            then
            end

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "ibzpromonthlyactioncommentprepareparam1"
            when
            then
                                ibzpromonthlyactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            ibzpromonthlyactioncommentdefault.set("product","0");
                            ibzpromonthlyactioncommentdefault.set("project","0");
                            ibzpromonthlyactioncommentdefault.set("read","0");
                            ibzpromonthlyactioncommentdefault.set("action","commented");
                            ibzpromonthlyactioncommentdefault.set("extra","");
                        update(ibzpromonthlyactioncommentdefault);//更新fact中变量值
            end