export default [
    'deptname',
    'lastrunresult',
    'version',
    'testrunsn',
    'lastrundate',
    'org',
    'updateby',
    'assignedto',
    'dept',
    'lastrunner',
    'status',
    'id',
    'orgname',
    'createby',
    'ibizcase',
    'task',
];
