package cn.ibizlab.pms.ibiz.logic.ibzdailyactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.IBZDailyAction ibzdailyactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IIBZDailyActionService iBzSysIbzdailyactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ibzdailyactioncommentbegin"
            when
            then
            end

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "ibzdailyactioncommentprepareparam1"
            when
            then
                                ibzdailyactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            ibzdailyactioncommentdefault.set("product","0");
                            ibzdailyactioncommentdefault.set("project","0");
                            ibzdailyactioncommentdefault.set("read","0");
                            ibzdailyactioncommentdefault.set("action","commented");
                            ibzdailyactioncommentdefault.set("extra","");
                        update(ibzdailyactioncommentdefault);//更新fact中变量值
            end