package cn.ibizlab.pms.ibiz.logic.ibzproprojectactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.IBZProProjectAction ibzproprojectactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IIBZProProjectActionService iBzSysIbzproprojectactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "ibzproprojectactioncommentprepareparam1"
            when
            then
                                ibzproprojectactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            ibzproprojectactioncommentdefault.set("product","0");
                            ibzproprojectactioncommentdefault.set("project","0");
                            ibzproprojectactioncommentdefault.set("read","0");
                            ibzproprojectactioncommentdefault.set("action","commented");
                            ibzproprojectactioncommentdefault.set("extra","");
                        update(ibzproprojectactioncommentdefault);//更新fact中变量值
            end

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ibzproprojectactioncommentbegin"
            when
            then
            end