package cn.ibizlab.pms.ibiz.logic.ibzcaseactionlogic.comment;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.IBZCaseAction ibzcaseactioncommentdefault;
global cn.ibizlab.pms.core.ibiz.service.IIBZCaseActionService iBzSysIbzcaseactionDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzcaseactioncommentbegin"
    when
    then
    end

//逻辑处理节点[设置默认参数]
rule "prepareparam1"
ruleflow-group "ibzcaseactioncommentprepareparam1"
    when
    then
    ibzcaseactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
    ibzcaseactioncommentdefault.set("product","0");
    ibzcaseactioncommentdefault.set("project","0");
    ibzcaseactioncommentdefault.set("read","0");
    ibzcaseactioncommentdefault.set("action","commented");
    ibzcaseactioncommentdefault.set("extra","");
    update(ibzcaseactioncommentdefault);//更新fact中变量值
    end

