package cn.ibizlab.pms.ibiz.logic.ibzproreleaseactionlogic.comment;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.IBZProReleaseAction ibzproreleaseactioncommentdefault;
global cn.ibizlab.pms.core.ibiz.service.IIBZProReleaseActionService iBzSysIbzproreleaseactionDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzproreleaseactioncommentbegin"
    when
    then
    end

//逻辑处理节点[设置默认参数]
rule "prepareparam1"
ruleflow-group "ibzproreleaseactioncommentprepareparam1"
    when
    then
    ibzproreleaseactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
    ibzproreleaseactioncommentdefault.set("product","0");
    ibzproreleaseactioncommentdefault.set("project","0");
    ibzproreleaseactioncommentdefault.set("read","0");
    ibzproreleaseactioncommentdefault.set("action","commented");
    ibzproreleaseactioncommentdefault.set("extra","");
    update(ibzproreleaseactioncommentdefault);//更新fact中变量值
    end

