package cn.ibizlab.pms.ibizpro.logic.ibzprosequencelogic.installseqfunc;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibizpro.domain.IBZProSequence ibzprosequenceinstallseqfuncdefault;
global cn.ibizlab.pms.core.ibizpro.service.IIBZProSequenceService iBzSysIbzprosequenceDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzprosequenceinstallseqfuncbegin"
    when
    then
    end

