package cn.ibizlab.pms.ibiz.logic.ibzproweeklyactionlogic.comment;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.IBZProWeeklyAction ibzproweeklyactioncommentdefault;
global cn.ibizlab.pms.core.ibiz.service.IIBZProWeeklyActionService iBzSysIbzproweeklyactionDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[设置默认参数]
rule "prepareparam1"
ruleflow-group "ibzproweeklyactioncommentprepareparam1"
    when
    then
    ibzproweeklyactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
    ibzproweeklyactioncommentdefault.set("product","0");
    ibzproweeklyactioncommentdefault.set("project","0");
    ibzproweeklyactioncommentdefault.set("read","0");
    ibzproweeklyactioncommentdefault.set("action","commented");
    ibzproweeklyactioncommentdefault.set("extra","");
    update(ibzproweeklyactioncommentdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzproweeklyactioncommentbegin"
    when
    then
    end

