package cn.ibizlab.pms.ibiz.logic.ibztestreportactionlogic.comment;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.pms.util.errors.BadRequestAlertException;
global cn.ibizlab.pms.core.ibiz.domain.IBZTestReportAction ibztestreportactioncommentdefault;
global cn.ibizlab.pms.core.ibiz.service.IIBZTestReportActionService iBzSysIbztestreportactionDefaultService;
global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibztestreportactioncommentbegin"
    when
    then
    end

//逻辑处理节点[设置默认参数]
rule "prepareparam1"
ruleflow-group "ibztestreportactioncommentprepareparam1"
    when
    then
    ibztestreportactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
    ibztestreportactioncommentdefault.set("product","0");
    ibztestreportactioncommentdefault.set("project","0");
    ibztestreportactioncommentdefault.set("read","0");
    ibztestreportactioncommentdefault.set("action","commented");
    ibztestreportactioncommentdefault.set("extra","");
    update(ibztestreportactioncommentdefault);//更新fact中变量值
    end

