package cn.ibizlab.pms.ibiz.logic.productplanactionlogic.comment;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.pms.util.errors.BadRequestAlertException;
                global cn.ibizlab.pms.core.ibiz.domain.ProductPlanAction productplanactioncommentdefault;
        global cn.ibizlab.pms.core.ibiz.service.IProductPlanActionService iBzSysProductplanactionDefaultService;
        global cn.ibizlab.pms.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productplanactioncommentbegin"
            when
            then
            end

            //逻辑处理节点[设置默认参数]
            rule "prepareparam1"
            ruleflow-group "productplanactioncommentprepareparam1"
            when
            then
                                productplanactioncommentdefault.set("actor",curuser.getSessionParams().get("srfloginname"));
                            productplanactioncommentdefault.set("product","0");
                            productplanactioncommentdefault.set("project","0");
                            productplanactioncommentdefault.set("read","0");
                            productplanactioncommentdefault.set("action","commented");
                            productplanactioncommentdefault.set("extra","");
                        update(productplanactioncommentdefault);//更新fact中变量值
            end